#!/bin/sh 
PS1='(gabriel) '
export PATH='/Users/kca/miniconda3/envs/spinstall/envs/gabriel/bin:/Users/kca/miniconda3/envs/spinstall/bin:/Users/kca/miniconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin'
export CONDA_PREFIX='/Users/kca/miniconda3/envs/spinstall/envs/gabriel'
export CONDA_SHLVL='2'
export CONDA_DEFAULT_ENV='gabriel'
export CONDA_PROMPT_MODIFIER='(gabriel) '
export CONDA_PREFIX_1='/Users/kca/miniconda3/envs/spinstall'
export CONDA_STACKED_2='true'
export CONDA_EXE='/Users/kca/miniconda3/envs/spinstall/bin/conda'
export _CE_M=''
export _CE_CONDA=''
export CONDA_PYTHON_EXE='/Users/kca/miniconda3/envs/spinstall/bin/python'
